name: YC Function CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-function
          path: target/serverless.url-shorner-1.0-SNAPSHOT.jar

  deploy:
    name: Deploy to Yandex Cloud
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-function

      - name: Deploy Function
        uses: yc-actions/yc-sls-function@v1.0.1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: 'url-shortner-java'
          runtime: 'java17'
          memory: '256Mb'
          execution-timeout: '10s'
          entrypoint: 'com.nedonil.urlshort.UrlShortnerServlet'
          include: |
            serverless.url-shorner-1.0-SNAPSHOT.jar
          exclude: |
            **/*.java
          environment: |
            DATABASE=${{ secrets.DB_NAME }}
            ENDPOINT=${{ secrets.DB_ENDPOINT }}
            IAM_TOKEN=${{ secrets.IAM_TOKEN }}