name: YC Function CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify --file pom.xml
  deploy:
    name: Deploy to Yandex Cloud
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Function
        uses: yc-actions/yc-sls-function@v1.0.1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: 'url-shortner-java'
          runtime: 'java21'
          memory: '128Mb'
          execution-timeout: '10s'
          entrypoint: 'com.nedonil.urlshort.UrlShortnerServlet'
          environment: |
            DATABASE=${{ secrets.DB_NAME }}
            ENDPOINT=${{ secrets.DB_ENDPOINT }}
            IAM_TOKEN=${{ secrets.IAM_TOKEN }}